{{- if .Values.docs.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "discordpim.fullname" . }}-docs
  {{- with .Values.docs.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.docs.ingress.className }}
  ingressClassName: {{ .Values.docs.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.docs.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "discordpim.fullname" $ }}-docs
                port:
                  number: {{ $.Values.docs.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.docs.ingress.tls }}
  tls:
    {{ toYaml .Values.docs.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}

