apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discordpim.fullname" . }}-app-data
  labels:
    app: {{ include "discordpim.name" . }}
    component: app
spec:
  accessModes: {{ toYaml .Values.app.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}

