apiVersion: v1
kind: Service
metadata:
  name: {{ include "discordpim.fullname" . }}-docs
  labels:
    app: {{ include "discordpim.name" . }}
    component: docs
spec:
  type: {{ .Values.docs.service.type }}
  ports:
    - port: {{ .Values.docs.service.port }}
      targetPort: {{ .Values.docs.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "discordpim.name" . }}
    component: docs

