apiVersion: v1
kind: Service
metadata:
  name: {{ include "discordpim.fullname" . }}-app
  labels:
    app: {{ include "discordpim.name" . }}
    component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "discordpim.name" . }}
    component: app

